const DONE_FETCHING_REPORTS = 'DONE_FETCHING_REPORTS';
const ERROR_FETCHING_REPORTS = 'ERROR_FETCHING_REPORTS';
const FETCH_REPORTS = 'FETCH_REPORTS';

const DONE_FETCHING_REPORT = 'DONE_FETCHING_REPORT';
const ERROR_FETCHING_REPORT = 'ERROR_FETCHING_REPORT';
const FETCH_REPORT = 'FETCH_REPORT';

const ADD_REPORT = 'ADD_REPORT';
const ERROR_ADDING_REPORT = 'ERROR_ADDING_REPORT';
const DONE_ADDING_REPORT = 'DONE_ADDING_REPORT';

const ADD_CLAIM = 'ADD_CLAIM';
const ERROR_ADDING_CLAIM = 'ERROR_ADDING_CLAIM';
const DONE_ADDING_CLAIM = 'DONE_ADDING_CLAIM';

const FETCH_CLAIMS = 'FETCH_CLAIMS';
const DONE_FETCHING_CLAIMS = 'DONE_FETCHING_CLAIMS';
const ERROR_FETCHING_CLAIMS = 'ERROR_FETCHING_CLAIMS';

const ANSWER_CLAIM = 'ANSWER_CLAIM';
const DONE_ANSWERING_CLAIM = 'DONE_ANSWERING_CLAIM';
const ERROR_ANSWERING_CLAIM = 'ERROR_ANSWERING_CLAIM';

export {
  DONE_FETCHING_REPORTS,
  ERROR_FETCHING_REPORTS,
  FETCH_REPORTS,
  DONE_FETCHING_REPORT,
  ERROR_FETCHING_REPORT,
  FETCH_REPORT,
  DONE_ADDING_REPORT,
  ADD_REPORT,
  ERROR_ADDING_REPORT,
  DONE_ADDING_CLAIM,
  ADD_CLAIM,
  ERROR_ADDING_CLAIM,
  FETCH_CLAIMS,
  DONE_FETCHING_CLAIMS,
  ERROR_FETCHING_CLAIMS,
  ERROR_ANSWERING_CLAIM,
  DONE_ANSWERING_CLAIM,
  ANSWER_CLAIM,
};
