const DONE_FETCHING_REPORTS = 'DONE_FETCHING_REPORTS';
const ERROR_FETCHING_REPORTS = 'ERROR_FETCHING_REPORTS';
const FETCH_REPORTS = 'FETCH_REPORTS';

export {
  DONE_FETCHING_REPORTS,
  ERROR_FETCHING_REPORTS,
  FETCH_REPORTS
};
