const DONE_FETCHING_REPORTS = 'DONE_FETCHING_REPORTS';
const ERROR_FETCHING_REPORTS = 'ERROR_FETCHING_REPORTS';
const FETCH_REPORTS = 'FETCH_REPORTS';

const DONE_FETCHING_REPORT = 'DONE_FETCHING_REPORT';
const ERROR_FETCHING_REPORT = 'ERROR_FETCHING_REPORT';
const FETCH_REPORT = 'FETCH_REPORT';

const ADD_REPORT = 'ADD_REPORT';
const ERROR_ADDING_REPORT = 'ERROR_ADDING_REPORT';
const DONE_ADDING_REPORT = 'DONE_ADDING_REPORT';

export {
  DONE_FETCHING_REPORTS,
  ERROR_FETCHING_REPORTS,
  FETCH_REPORTS,
  DONE_FETCHING_REPORT,
  ERROR_FETCHING_REPORT,
  FETCH_REPORT,
  DONE_ADDING_REPORT,
  ADD_REPORT,
  ERROR_ADDING_REPORT
};
